// Prefecture dimension: pick a 都道府県 to see all 百名店 restaurants in it
// across genres. The data is generated by scripts/gen-prefectures.mjs.

export type Prefecture = {
  key: string; // ascii key, matches public/data/pref/<key>.json
  ja: string; // Japanese name, e.g. "東京都"
  count: number;
};

export type PrefectureGroup = {
  region: string; // e.g. "関東"
  items: Prefecture[];
};

import { PREFECTURE_GROUPS } from "./prefectures.generated";

export const PREFECTURE_GROUPS_LIST: PrefectureGroup[] = PREFECTURE_GROUPS;
