// AUTO-GENERATED by scripts/gen-prefectures.mjs — do not edit by hand.
import type { PrefectureGroup } from "./prefectures";

export const PREFECTURE_GROUPS: PrefectureGroup[] = [
  {
    "region": "北海道",
    "items": [
      {
        "key": "hokkaido",
        "ja": "北海道",
        "count": 331
      }
    ]
  },
  {
    "region": "東北",
    "items": [
      {
        "key": "aomori",
        "ja": "青森県",
        "count": 24
      },
      {
        "key": "iwate",
        "ja": "岩手県",
        "count": 24
      },
      {
        "key": "miyagi",
        "ja": "宮城県",
        "count": 63
      },
      {
        "key": "akita",
        "ja": "秋田県",
        "count": 47
      },
      {
        "key": "yamagata",
        "ja": "山形県",
        "count": 28
      },
      {
        "key": "fukushima",
        "ja": "福島県",
        "count": 37
      }
    ]
  },
  {
    "region": "関東",
    "items": [
      {
        "key": "ibaraki",
        "ja": "茨城県",
        "count": 41
      },
      {
        "key": "tochigi",
        "ja": "栃木県",
        "count": 46
      },
      {
        "key": "gunma",
        "ja": "群馬県",
        "count": 37
      },
      {
        "key": "saitama",
        "ja": "埼玉県",
        "count": 148
      },
      {
        "key": "chiba",
        "ja": "千葉県",
        "count": 134
      },
      {
        "key": "tokyo",
        "ja": "東京都",
        "count": 2039
      },
      {
        "key": "kanagawa",
        "ja": "神奈川県",
        "count": 414
      }
    ]
  },
  {
    "region": "中部",
    "items": [
      {
        "key": "niigata",
        "ja": "新潟県",
        "count": 45
      },
      {
        "key": "toyama",
        "ja": "富山県",
        "count": 30
      },
      {
        "key": "ishikawa",
        "ja": "石川県",
        "count": 69
      },
      {
        "key": "fukui",
        "ja": "福井県",
        "count": 20
      },
      {
        "key": "yamanashi",
        "ja": "山梨県",
        "count": 21
      },
      {
        "key": "nagano",
        "ja": "長野県",
        "count": 80
      },
      {
        "key": "gifu",
        "ja": "岐阜県",
        "count": 80
      },
      {
        "key": "shizuoka",
        "ja": "静岡県",
        "count": 78
      },
      {
        "key": "aichi",
        "ja": "愛知県",
        "count": 529
      }
    ]
  },
  {
    "region": "近畿",
    "items": [
      {
        "key": "mie",
        "ja": "三重県",
        "count": 56
      },
      {
        "key": "shiga",
        "ja": "滋賀県",
        "count": 37
      },
      {
        "key": "kyoto",
        "ja": "京都府",
        "count": 434
      },
      {
        "key": "osaka",
        "ja": "大阪府",
        "count": 933
      },
      {
        "key": "hyogo",
        "ja": "兵庫県",
        "count": 273
      },
      {
        "key": "nara",
        "ja": "奈良県",
        "count": 61
      },
      {
        "key": "wakayama",
        "ja": "和歌山県",
        "count": 17
      }
    ]
  },
  {
    "region": "中国",
    "items": [
      {
        "key": "tottori",
        "ja": "鳥取県",
        "count": 3
      },
      {
        "key": "shimane",
        "ja": "島根県",
        "count": 8
      },
      {
        "key": "okayama",
        "ja": "岡山県",
        "count": 26
      },
      {
        "key": "hiroshima",
        "ja": "広島県",
        "count": 83
      },
      {
        "key": "yamaguchi",
        "ja": "山口県",
        "count": 9
      }
    ]
  },
  {
    "region": "四国",
    "items": [
      {
        "key": "tokushima",
        "ja": "徳島県",
        "count": 16
      },
      {
        "key": "kagawa",
        "ja": "香川県",
        "count": 119
      },
      {
        "key": "ehime",
        "ja": "愛媛県",
        "count": 24
      },
      {
        "key": "kochi",
        "ja": "高知県",
        "count": 18
      }
    ]
  },
  {
    "region": "九州・沖縄",
    "items": [
      {
        "key": "fukuoka",
        "ja": "福岡県",
        "count": 251
      },
      {
        "key": "saga",
        "ja": "佐賀県",
        "count": 19
      },
      {
        "key": "nagasaki",
        "ja": "長崎県",
        "count": 29
      },
      {
        "key": "kumamoto",
        "ja": "熊本県",
        "count": 47
      },
      {
        "key": "oita",
        "ja": "大分県",
        "count": 21
      },
      {
        "key": "miyazaki",
        "ja": "宮崎県",
        "count": 46
      },
      {
        "key": "kagoshima",
        "ja": "鹿児島県",
        "count": 40
      },
      {
        "key": "okinawa",
        "ja": "沖縄県",
        "count": 62
      }
    ]
  }
];
