// AUTO-GENERATED by scripts/gen-sets.mjs — do not edit by hand.
// Run `node scripts/gen-sets.mjs` after scraping more sets.
import type { AwardSet } from "./sets";

export const GENERATED_SETS: AwardSet[] = [
  {
    "slug": "curry_tokyo",
    "label": "カレー 東京",
    "genre": "カレー"
  },
  {
    "slug": "tonkatsu",
    "label": "とんかつ",
    "genre": "とんかつ"
  },
  {
    "slug": "ramen_hokkaido",
    "label": "ラーメン 北海道",
    "genre": "ラーメン"
  },
  {
    "slug": "ramen_tokyo",
    "label": "ラーメン 東京",
    "genre": "ラーメン"
  },
  {
    "slug": "yakiniku_tokyo",
    "label": "焼肉 東京",
    "genre": "焼肉"
  },
  {
    "slug": "soba_east",
    "label": "そば 東日本",
    "genre": "そば"
  },
  {
    "slug": "french_tokyo",
    "label": "フレンチ 東京",
    "genre": "フレンチ"
  },
  {
    "slug": "italian_tokyo",
    "label": "イタリアン 東京",
    "genre": "イタリアン"
  },
  {
    "slug": "tempura",
    "label": "天ぷら",
    "genre": "天ぷら"
  },
  {
    "slug": "sushi_tokyo",
    "label": "寿司 東京",
    "genre": "寿司"
  },
  {
    "slug": "sushi_east",
    "label": "寿司 東日本",
    "genre": "寿司"
  },
  {
    "slug": "unagi",
    "label": "うなぎ",
    "genre": "うなぎ"
  }
];
