// Generate app/sets.generated.ts from the index catalog, including only the
// sets that have actually been scraped (a public/data/v3/<slug>.json exists).
// Re-run this after scraping more sets.
//
//   node scripts/gen-sets.mjs

import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadSetCatalog } from "./lib/catalog.mjs";

const DATA_DIR = path.join(process.cwd(), "public", "data", "v3");
const OUT_FILE = path.join(process.cwd(), "app", "sets.generated.ts");

const catalog = await loadSetCatalog();

const files = await readdir(DATA_DIR).catch(() => []);
const scraped = new Set(
  files.filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, "")),
);

const sets = catalog
  .filter((c) => scraped.has(c.slug))
  .map(({ slug, label, genre }) => ({ slug, label, genre }));

const body = `// AUTO-GENERATED by scripts/gen-sets.mjs — do not edit by hand.
// Run \`node scripts/gen-sets.mjs\` after scraping more sets.
import type { AwardSet } from "./sets";

export const GENERATED_SETS: AwardSet[] = ${JSON.stringify(sets, null, 2)};
`;

await writeFile(OUT_FILE, body);
console.log(`Wrote ${sets.length}/${catalog.length} sets -> ${OUT_FILE}`);
